### ISSUE TITLE
Decorators should not be mocked when testing

### ISSUE THREAD

**Issue by patricksnape** [menpo/h5it#1]
For example, in Menpo, when using the `@ndfeature` decorator, it attempts to mock it and then fails with a rather unhelpful error message.

**Comment by jabooth** [comment]
Tried going down the road of adding a `mock_excludes` kwarg to sort this:

``` python
sc = SerializableCallable(foo, modules=[menpo.feature], 
                          mock_excludes=[ndfeature, imgfeature])
```

problem is, the excluded decorator's namespace is not mocked - starts getting pretty complex to try and do these nested mockings I think...

Unless we have a bright idea, I think we might just have to refer to the simpler testing approach:

``` python
sc = SerializableCallable(foo, modules=[menpo.feature], 
                          test_args=[np.ones(128, 128, 1), 
                          test_kwargs={'flag_it_up': True})
```

user provides an explicit set of args/kwargs to pass through the function in a test. If any exception is raised, the test fails. Output is ignored. Thoughts?

**Comment by jabooth** [comment]
This is now to be handled by the [serializablecallable](https://github.com/menpo/serializablecallable) project.
